### ISSUE TITLE
Submission  스크립트 분석

### ISSUE THREAD

**Issue by dc0953** [ltechkorea/mlperf-inference#68]
- [ ] filter-errors.py
  - v0.7 제출의 로그 파일에서 수동으로 확인된 오류를 제거하는 도구입니다.
  - v0.7 까지만 사용된 파일로 예상,, 추가확인 필요,,
 ---------------------------------------------------

- [x] generate-final-report.py
 - 검사기 csv 출력에서 최종 결과 스프레드시트를 생성하는 도구입니다.
   결과로 생성된 Excel 파일을 Google 시트로 가져올 수 있습니다.
 ---------------------------------------------------

- [x] log_parser.py
  -  submission-checker.py 에서 필요한 모듈만 불러쓰는 파일
 ---------------------------------------------------

- [x] pack_submission.sh
  - 제출 저장소의 암호화된 tarball을 함께 제출합니다. 
  - 암호화된 tarball의 암호 해독 및 SHA1 해시를 MLPerf에 전송합니다.
  - SUBMITTER=COMPANY 변경
  - bashpack_submission.sh --pack입니다.
  - 이 명령은 암호화 암호를 입력한 다음 확인하라는 메시지를 표시합니다.
  - 이 명령의 실행이 완료되면 다음과 같은 2개의 파일이 생성됩니다.
  - 'mlperf_submission_${ 입니다.SUMBITTER}.tar.gz' - AES256으로 암호화된 암호화된 tarball입니다.
  - 'mlperf_submission_${ 입니다.SUMBITTER.sha1' - 암호화된 tarball의 sha1 해시를 포함하는 텍스트 파일입니다.
  - 제출물이 성공적으로 포장되었는지 테스트하려면 다음을 실행합니다.
  - bash path/to/pack_submission.sh --bash 경로입니다.
  - MLPerf 추론 결과 의장과 공유해야 할 3가지 사항입니다.
      1. 제출 내역은 다음과 같습니다.
       1-1. mlperf_submission_${ 입니다.SUMBITTER}.tar.gz' - AES256으로 
            암호화된 암호화된 tarball입니다.
       1-2. mlperf_submission_${ 입니다.SUMBITTER.sha1' - 암호화된 tarball의 sha1 해시를 
            포함하는 텍스트 파일입니다.
       1-3. 암호 해독을 합니다.

  - 제출 기한 전에 Tarball을 **퍼블릭 클라우드 스토리지(확인필요)**에 업로드합니다.
  - 링크를 항목(1-1, 1.2, 1.3) 함께 MLCommons 제출 주소로 이메일로 보냅니다. 
  -  submissions@mlcommons.org
  - submission_checker_log의 마지막 두 줄을 포함합니다.같은 txt입니다.
  - 유효한 제출의 피상적인 증거로서 이메일 본문 아래에 있습니다.
     -  INFO:main:Results=265, NoResults=0
     -  INFO:main:SUMMARY: submission looks OK
---------------------------------------------------

- [x] submission-checker.py
 - 제출디렉토리 생성 후 검사 단계
  - python ../../tools/submission/submission-checker.py --input {SUBMISSION_ROOT} > {SUBMISSION_DIR}/submission-checker.log 2>&1 
  - cat {SUBMISSION_DIR}/submission-checker.log
---------------------------------------------------

- [x] truncate_accuracy_log.py 
  - mlperf_log_accuracy.json 4K 사이즈 줄이는 과정 / 2가지 방법으로 실행 가능 
  - 1.  기존 디렉토리를 선택하고 수정된 json 파일로 완전히 새로운 제출 디렉토리 생성
       python tools/submission/truncate_accuracy_log.py --input ORIGINAL_SUBMISSION_DIRECTORY --submitter MY_ORG \\
        --output NEW_SUBMISSION_DIRECTORY
  - 2. 수정된 파일을 백업 디렉토리로 복사하여 기존파일을 수정
        python tools/submission/truncate_accuracy_log.py --input ROOT_OF_SUBMISSION_DIRECTORY --submitter MY_ORG \\
        --backup MY_SUPER_SAFE_STORAGE 

---------------------------------------------------

진행 예상 순서 
1. 제출 디렉토리 생성후 truncate_accuray_log.json 파일 사이즈 줄이기
2. submission-checker.py 로 최종 확인
3. pack_submission.sh 로 tarball 을 만든 뒤 submissions@mlcommons.org 과 
   퍼블릭 클라우드 스토리지 올려 파일 전송

**Comment by dc0953** [comment]
A URL to the location in public blob storage of an encrypted tarball containing the open/* and closed/* submission files. Any storage mechanism that supports curl may be used.

**Comment by lyly403** [comment]
--backup =  directory to original accuracy log ( 
--input    = original submission directory
--output = new submission directory
